um = input()
dois = input()
um = um.split()
dois = dois.split()
um[0] = float(um[0])
um[1] = float(um[1])
dois[0] = float(dois[0])
dois[1] = float(dois[1])
print(round(((dois[0] - um[0]) ** 2 + (dois[1]  - um[1]) ** 2) ** 0.5, 4))